git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme base16-256 -s

# https://github.com/jesseduffield/lazygit/issues/3064#issue-1938460094
os:
  openLink: open "$(echo "{{link}}" | sed 's/%2F/\//g')"

gui:
  showIcons: true
  enlargedSideViewLocation: top
  animateExplosion: true
