name: dotbox

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t dotbox dotbox

      - name: Get release version
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}

      - name: Publish to the Docker Hub
        run: |
            docker login --username "${{ github.actor }}" --password "${{ secrets.DOCKER_HUB_TOKEN }}"
            docker tag dotbox "${{ github.actor }}/dotbox:${{ env.RELEASE_VERSION }}"
            docker push "${{ github.actor }}/dotbox:${{ env.RELEASE_VERSION }}"
